### ISSUE TITLE
<Input> disable in <TextField> not working

### ISSUE THREAD

**Issue by Fa-So** [material-components/material-components-web-react#847] opened 2019-05-03 12:34 UTC
I get the following error when i toggle  disable <TextField> input:
```
Uncaught Error: MDCReactTextField: The input did not render properly
    at Object.getNativeInput (VM3816 index.js:300)
    at MDCTextFieldFoundation.getNativeInput_ (VM3816 index.js:559)
    at MDCTextFieldFoundation.setDisabled (VM3816 index.js:531)
    at Input.226.Input.componentDidUpdate (VM3816 index.js:775)
    at commitLifeCycles (VM1337 react-dom.development.js:17303)
    at commitAllLifeCycles (VM1337 react-dom.development.js:18690)
    at HTMLUnknownElement.callCallback (VM1337 react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (VM1337 react-dom.development.js:199)
    at invokeGuardedCallback (VM1337 react-dom.development.js:256)
    at commitRoot (VM1337 react-dom.development.js:18902)
    at eval (VM1337 react-dom.development.js:20372)
    at Object.unstable_runWithPriority (VM1344 scheduler.development.js:255)
    at completeRoot (VM1337 react-dom.development.js:20371)
    at performWorkOnRoot (VM1337 react-dom.development.js:20300)
    at performWork (VM1337 react-dom.development.js:20208)
    at performSyncWork (VM1337 react-dom.development.js:20182)
    at interactiveUpdates$1 (VM1337 react-dom.development.js:20449)
    at interactiveUpdates (VM1337 react-dom.development.js:2170)
    at dispatchInteractiveEvent (VM1337 react-dom.development.js:4882)
```

[This is sample code:](https://codesandbox.io/s/92n2v7oyy4)

```
import React, { useState } from "react";
import { render } from "react-dom";
import TextField, { Input } from "@material/react-text-field";
import Button from "@material/react-button";

import "./styles.css";

const App = () => {
  const [toggle, setToggle] = useState(false);
  const onToggle = () => {
    setToggle(!toggle);
  };
  return (
    <div className="App">
      <TextField label="test">
        <Input disabled={toggle} value="1234" />
      </TextField>
      <Button outlined onClick={onToggle}>
        toggle disable
      </Button>
    </div>
  );
};

const rootElement = document.getElementById("root");
render(<App />, rootElement);
```

**Comment by TroyTae** [comment] 2019-05-03 16:05
@Fa-So 
Thank you for find this issue!
I'm fixing on it.

**Comment by moog16** [comment] 2019-05-03 17:18
Thanks for hoping on the fix @TroyTae - what is the actual root cause?

**Comment by TroyTae** [comment] 2019-05-04 06:23
@moog16 
https://reactjs.org/docs/refs-and-the-dom.html#caveats-with-callback-refs
See this please :)

**Comment by TroyTae** [comment] 2019-05-04 06:30
Maybe we need to consider observer or singleton pattern for preventing like this situation.

**Comment by moog16** [comment] 2019-05-06 16:00
@TroyTae are there other places in MDC React where we use callback refs? Is that what you're referring to?

**Comment by moog16** [comment] 2019-05-06 16:00
Closing with #848

**Closed by moog16** 2019-05-06 16:00 UTC

**Comment by TroyTae** [comment] 2019-05-07 02:55
@moog16 
No no, I just worried when we need to share three or more components each other.
In this case, there are only two components.
I want to say if we have more than three, I think you will need another plan.
