### ISSUE TITLE
Regression: Select does't change value on option tag click (Firefox)

### ISSUE THREAD

**Issue by SleeplessByte** [material-components/material-components-web-react#935] opened 2019-06-17 08:46 UTC
Regression of #476 

Doesn't work with 0.12.0+ (0.13.0+).
Firefox 67.0.2.

Same issue as referenced issue. Keyboard control works.

**Comment by moog16** [comment] 2019-06-17 20:45
Thanks for reporting issue - I investigated, and its not a true regression, meaning the issue isn't the same as before. I believe this might be an issue that a new version o FireFox introduced. See https://stackblitz.com/edit/react-select-mdc?file=index.js.

**Comment by SleeplessByte** [comment] 2019-06-17 21:36
Let me know if there is anything I can do from my end.

**Comment by moog16** [comment] 2019-06-17 21:46
I remember seeing an issue in MDC Web that we'll be deprecating the native select. So if MDC Web deprecates it, we will most likely ditch support as well.

I'm in a holding pattern on the NativeSelect. If you would like to fix this issue, please feel free. I can work with you to get the fix in.

**Comment by SleeplessByte** [comment] 2019-06-18 09:59
I don't mind ditching it, if I knew how.

A temporary patch is fine with me as well, but I don't know where to start as you say: `MDC React does not manipulate the onChange event`. It does seem that indeed `event.target.value`. I'm wondering if we can grab it from somewhere else...

**Comment by moog16** [comment] 2019-06-18 17:17
What do you mean, "if I knew how"? The alternative is to use the `enhanced` select. Although you do not get the native picker on native.

**Comment by SleeplessByte** [comment] 2019-07-07 13:09
That's exactly what I wanted to hear. I'm fine with using `enhanced`, especially if the team is going to drop native anyway.

> I'm in a holding pattern on the `NativeSelect`. If you would like to fix this issue, please feel free. I can work with you to get the fix in.

Feel free to close/keep this open to track the issue. I think there are plenty of reasons to keep supporting NativeSelect, but we don't need it right now.

**Comment by moog16** [comment] 2019-07-08 17:02
I'm thinking I will close the issue, until the NativeSelect is removed from MDC Web. Then we can open a new issue for that. Thanks!

**Closed by moog16** 2019-07-08 17:02 UTC

**Comment by mgr34** [comment] 2019-10-03 16:13
I would vote to reopen. A hacky solution I am currently  using is this

```js
<Select onChange={e => updateLocation(e.target.value)} onClick={e => updateLocation(e.target.value) } .../>
```

in updateLocation I am looking at the currentValue and if === just return and exit the function. This is necessary for my application because I am using Select to fire a network request. 

onClick will fire 2x. When you Click on select the first time to open and again to close.  You want to keep the onChange because that still works as expected with a keyboard only approach.
