### ISSUE TITLE
Text-Field setState problem

### ISSUE THREAD

**Issue by benn983** [material-components/material-components-web-react#275] opened 2018-09-24 09:46 UTC
Hi the textField component gives me this error when i click on it. This error is fired only with the standard component. Whit the outlined all works correctly apart for the style(i think I'm wrong there).
This is my code
the error:
![schermata del 2018-09-24 11-44-35](https://user-images.githubusercontent.com/26009890/45945917-6ce78000-bfef-11e8-8983-d862979e3b29.png)
The piece of code:
`<TextField
          className="search"
          label={props.text}
          trailingIcon={<MaterialIcon icon="search" />}
        >
          <Input
            value={props.value}
            onChange={event => 
              props.change(event);
            }
          />
        </TextField>`

**Comment by moog16** [comment] 2018-09-25 00:39
@benn983 I tried running your component in a test app. I attached it in the issue. 

directions
1. open in terminal
1. `yarn`
1. `yarn start`

browser should open to localhost:3000. It looks like text field is working as designed. My only confusion is what your `props` variable is coming from. That could be the source of your problem. Also you don't need a semi-colon in your `onChange` method.

[testapp-copy.zip](https://github.com/material-components/material-components-web-react/files/2413366/testapp-copy.zip)

**Comment by sashless** [comment] 2018-09-25 08:55
@moog16 I tried this using the device toolbar in chrome and on a real mobile device and can reproduce that there. It is impossible to set any value.

![screen shot 2018-09-25 at 10 53 28](https://user-images.githubusercontent.com/1218924/46003724-7d602f00-c0b1-11e8-8abc-1c21da9d3fd1.png)

**Comment by sashless** [comment] 2018-09-25 09:32
The problem seems to be in `material/textfield` where `clientX` and `clientY` is missing in the event and the value `normalizedX` passend to `setLineRippleTransformOrigin` is `NaN`.


```js
 setTransformOrigin(evt) {
    const targetClientRect = evt.target.getBoundingClientRect();
    const evtCoords = {x: evt.clientX, y: evt.clientY};
    const normalizedX = evtCoords.x - targetClientRect.left;
    this.adapter_.setLineRippleTransformOrigin(normalizedX); // using here a number or null is fixing the problem
  }
```

**Comment by moog16** [comment] 2018-09-25 16:29
@sashless - got it. It looks like I can also reproduce on Mac OSx Chrome when you use the mobile mode. We'll start investigating

**Comment by moog16** [comment] 2018-09-25 20:39
This is actually an MDC Web bug: I've filed here: https://github.com/material-components/material-components-web/issues/3643.

In the interim until that is fixed in MDC Web, I think we can get around this by checking `isNaN()` in the line ripple componentDidUpdate:

```
if (this.props.rippleCenter !== prevProps.rippleCenter && !isNaN(this.props.rippleCenter) {
      this.foundation_.setRippleCenter(this.props.rippleCenter);
}
```

This will unfortunately remove this feature for mobile browsers, but at least it won't throw an error.

**Closed** 2018-09-25 23:42 UTC
Labels: bug
