### ISSUE TITLE
Select label not floating

### ISSUE THREAD

**Issue by ndtreviv** [material-components/material-components-web-react#912] opened 2019-06-06 09:11 UTC
# Code:
```
          <Select
            label="Operator"
            value={operator || ""}
            onChange={e => {
              this.setState({ operator: e.target.value });
            }}
          >
            {selectedField.operators.map((operator, index) => {
              return (
                <Option key={index} value={operator}>
                  {operator}
                </Option>
              );
            })}
          </Select>
```

# Expected Behaviour
If there is no value, the field should show as empty.

# Actual Behaviour
The first Option is selected by default and the label does not float:

<img width="142" alt="Screenshot 2019-06-06 at 10 09 49" src="https://user-images.githubusercontent.com/1530653/59021153-3da63580-8843-11e9-98f8-7a58f0076c85.png">

**Comment by TroyTae** [comment] 2019-06-09 14:13
When no option matches the select's value, this situation is fired.
How about add disabled option?

**Comment by ndtreviv** [comment] 2019-06-10 08:22
Well there's definitely a value that matches. It wouldn't be showing if it didn't match...
```
{selectedField.operators.map((operator, index) => {
              return (
                <Option key={index} value={operator}>
                  {operator}
                </Option>
              );
            })}
```

In my humble opinion, with all input fields, the label should always float if they're populated with a value - even if it's the wrong one. I'd rather see an incorrect wrong value clearly than see an overlapping label.

**Comment by TroyTae** [comment] 2019-06-10 13:26
Ah I see, here is the label adapter code:
https://github.com/material-components/material-components-web-react/blob/master/packages/select/index.tsx#L231
And it looks label's float is managed by mdc-web.
If you wanna change some condition you need to change there!

**Comment by moog16** [comment] 2019-06-10 22:05
I'll look through this one too.

**Comment by TroyTae** [comment] 2019-06-11 05:49
https://github.com/material-components/material-components-web/blob/358546a375583bd0a90855e352767c54f926e3bb/packages/mdc-select/foundation.ts#L154

In mdc-web, label is floated when there is something value.

**Comment by ndtreviv** [comment] 2019-06-11 11:22
I think the problem lies in material-components-web.

I've mostly written a fix, but I'm still working out how to get the computed style of the element in the tests I've written. You'll probably do it faster, @moog16 and more inline with existing stuff in terms of methodology, no doubt, so I'll leave it to you!

**Comment by moog16** [comment] 2019-06-17 20:18
@ndtreviv - I thought this was related to the text-field, but it seems to be a totally different issue. How do you reproduce this? And what do you mean by "event if it's the wrong one."

**Comment by ndtreviv** [comment] 2019-06-18 13:36
I don't know why, but I can't reproduce it anymore. My codebase has moved on, and trying to reproduce with a stackblitz isn't working either. Maybe close this for now...? If I manage to successfully reproduce it again I'll nail down the conditions and post back.

**Comment by moog16** [comment] 2019-06-18 17:18
Ok - yeah I wasn't able to repro it either (we did find a solution for the text field). Closing :)

**Closed by moog16** 2019-06-18 17:18 UTC
